version: "3.8"

services:
  nexora-ai:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://nexora:nexora_password@postgres:5432/nexora_db
      - DEBUG=false
      - API_VERSION=v1
      - SERVICE_NAME=Nexora AI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN}
      - API_KEY=${API_KEY:-poc-key-123}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./storage:/app/storage
    restart: unless-stopped
    networks:
      - nexora-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=nexora_db
      - POSTGRES_USER=nexora
      - POSTGRES_PASSWORD=nexora_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexora -d nexora_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - nexora-network

volumes:
  postgres_data:

networks:
  nexora-network:
    driver: bridge
